spring.application.name=blog-service

# db/orm settings
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# db migrations
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.properties.hibernate.validator.apply_to_ddl=false

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
